version: '3.7'
volumes:
  kompra_db:
services:
  web:
    env_file:
      - .env
    build: .
    command: sleep infinity
    ports:
      - "3000:3000"
    depends_on:
      - db
    tty: true
    volumes:
      - .:/app
  db:
    image: docker.io/postgres
    volumes:
      - kompra_db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
  adminer:
    image: docker.io/adminer
    restart: always
    ports:
      - 8080:8080

